# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "acme-buildpacks/php"
version = "0.0.1"
name = "PHP dist"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
