# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "acme-buildpacks/composer"
version = "0.0.1"
name = "Composer Scaffold"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
